before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: SJSzApcw8MluT6CgNHr9V/kaEDtoJaVuR9RNkDOYVKkJbirz/d7rdX7TW2a8ouPGWeQqZJrxP0yjpRo2HX0+n+Tyn9k76lV8iM2XhV//lWFlDW1GgdBDQNQ43acjU8mYeEecYtKV1AfcractLCwQ+T50cUgAd80OC7iQsh+R5ySFi7Iq+srtGiJcpKZ2RhIPQNXuXQo8AaFBKcluMFEOSN1ChJdwTnXYoWTPQBJ+LU7Z9EZomEpC6YUPwX1iVrh03o3ZuWoRNnIwQiJFPHBTYSIoqXac3t0zZ1E+z+IZgc2Vjuxl6dAQN9LI6DJ5xIlrCGRSppnqVukKuhJYfScezAFin4graUJxTypuKYPHOpriL8KRct3uQttO1jiDXRN6M31Ti5IuV975Q7iNcDhaxiUE5K8QAbxwDDqVPiB5YEs5BXrCmItdDl8aJ66xG0RRBRdqHrMPFvY48LU7advYSrwhMk7YJE0BjDpunFOg9bJXrTkWy5wx0pnhiQICrmyK3HdztyGKEN2MP0i1XHqU94fwhu5VA/THllICIxVcRDz8+CCUAYjsTs19jiLl2E68ukrSTHqrnCLqNCr9It3IKKf+fdSwWyBs/BVzEJ5bnOXO14IRl0Fq9xHh8/6oKlP63BTSYKOzZ7QLA68PAevL7M3A4adhvOwiHYxg4SqQ2KA= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
